"""Crestron timezone definitions from ``TIMEZONE LIST`` command output."""

from __future__ import annotations

# (id, name, utc_offset_label)
TIMEZONES: list[tuple[str, str, str]] = [
    ("000", "Dateline Standard Time", "(UTC-12:00) International Date Line West"),
    ("002", "UTC-11", "(UTC-11:00) Coordinated Universal Time -11"),
    ("147", "Aleutian Standard Time", "(UTC-10:00) Aleutian Islands"),
    ("003", "Hawaiian Standard Time", "(UTC-10:00) Hawaii"),
    ("112", "Polynesia Standard Time", "(UTC-10:00) Tahiti"),
    ("100", "Marquesas Standard Time", "(UTC-09:30) Marquesas Islands"),
    ("004", "Alaskan Standard Time", "(UTC-09:00) Alaska"),
    ("151", "UTC-09", "(UTC-09:00) Coordinated Universal Time-09"),
    ("101", "Gambier Islands", "(UTC-09:00) Gambier"),
    ("005", "Pacific Standard Time", "(UTC-08:00) Pacific Time (US & Canada)"),
    ("006", "Pacific Standard Time (Mexico)", "(UTC-08:00) Baja California"),
    ("150", "UTC-08", "(UTC-08:00) Coordinated Universal Time-08"),
    ("099", "Pitcairn Islands Standard Time", "(UTC-08:00) Pitcairn Islands"),
    ("007", "Mountain Standard Time", "(UTC-07:00) Mountain Time (US & Canada)"),
    ("008", "US Mountain Standard Time", "(UTC-07:00) Arizona"),
    ("009", "Mountain Standard Time (Mexico)", "(UTC-07:00) La Paz, Mazatlan"),
    ("011", "Canada Central Standard Time", "(UTC-06:00) Saskatchewan"),
    ("012", "Central America Standard Time", "(UTC-06:00) Central America"),
    ("010", "Central Standard Time", "(UTC-06:00) Central Time (US & Canada)"),
    ("013", "Central Standard Time (Mexico)", "(UTC-06:00) Guadalajara, Mexico City, Monterrey"),
    ("102", "Easter Island Standard Time", "(UTC-06:00) Easter Island"),
    ("143", "Cuba Standard Time", "(UTC-05:00) Havana"),
    ("014", "Eastern Standard Time", "(UTC-05:00) Eastern Time (US & Canada)"),
    ("127", "Eastern Standard Time (Mexico)", "(UTC-05:00) Chetumal"),
    ("142", "Haiti Standard Time", "(UTC-05:00) Haiti"),
    ("016", "SA Pacific Standard Time", "(UTC-05:00) Bogota, Lima, Quito, Rio Branco"),
    ("152", "Turks and Caicos Standard Time", "(UTC-05:00) Turks and Caicos"),
    ("015", "US Eastern Standard Time", "(UTC-05:00) Indiana (East)"),
    ("018", "Atlantic Standard Time", "(UTC-04:00) Atlantic Time (Canada)"),
    ("021", "Central Brazilian Standard Time", "(UTC-04:00) Cuiaba"),
    ("020", "Pacific SA Standard Time", "(UTC-04:00) Santiago"),
    ("022", "Paraguay Standard Time", "(UTC-03:00) Asuncion"),
    ("019", "SA Western Standard Time", "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan"),
    ("017", "Venezuela Standard Time", "(UTC-04:00) Caracas"),
    ("023", "Newfoundland Standard Time", "(UTC-03:30) Newfoundland"),
    ("027", "Argentina Standard Time", "(UTC-03:00) Buenos Aires"),
    ("111", "Bahia Standard Time", "(UTC-03:00) Salvador"),
    ("024", "E. South America Standard Time", "(UTC-03:00) Brasilia"),
    ("026", "Greenland Standard Time", "(UTC-02:00) Greenland"),
    ("156", "Magallanes Standard Time", "(UTC-03:00) Punta Arenas"),
    ("028", "Montevideo Standard Time", "(UTC-03:00) Montevideo"),
    ("025", "SA Eastern Standard Time", "(UTC-03:00) Cayenne, Fortaleza"),
    ("138", "Saint Pierre Standard Time", "(UTC-03:00) Saint Pierre and Miquelon"),
    ("136", "Tocantins Standard Time", "(UTC-03:00) Araguaina"),
    ("029", "Mid-Atlantic Standard Time", "(UTC-02:00) Mid-Atlantic"),
    ("032", "UTC-02", "(UTC-02:00) Coordinated Universal Time -02"),
    ("031", "Azores Standard Time", "(UTC-01:00) Azores"),
    ("128", "Cabo Verde Standard Time", "(UTC-01:00) Cabo Verde Is."),
    ("036", "Coordinated Universal Time", "(UTC) Coordinated Universal Time"),
    ("033", "GMT Standard Time", "(UTC+00:00) Dublin, Edinburgh, Lisbon, London"),
    ("034", "Greenwich Standard Time", "(UTC+00:00) Monrovia, Reykjavik"),
    ("035", "Morocco Standard Time", "(UTC+01:00) Casablanca"),
    ("037", "Central Europe Standard Time", "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague"),
    ("038", "Central European Standard Time", "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb"),
    ("039", "Romance Standard Time", "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris"),
    ("155", "Sao Tome Standard Time", "(UTC+00:00) Sao Tome"),
    ("041", "W. Central Africa Standard Time", "(UTC+01:00) West Central Africa"),
    ("040", "W. Europe Standard Time", "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"),
    ("043", "E. Europe Standard Time", "(UTC+02:00) Chisinau"),
    ("044", "Egypt Standard Time", "(UTC+02:00) Cairo"),
    ("045", "FLE Standard Time", "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius"),
    ("046", "GTB Standard Time", "(UTC+02:00) Athens, Bucharest"),
    ("048", "Jerusalem Standard Time", "(UTC+02:00) Jerusalem"),
    ("049", "Jordan Standard Time", "(UTC+03:00) Amman"),
    ("113", "Libya Standard Time", "(UTC+02:00) Tripoli"),
    ("050", "Middle East Standard Time", "(UTC+02:00) Beirut"),
    ("042", "Namibia Standard Time", "(UTC+02:00) Windhoek"),
    ("121", "Russia TZ 1 Standard Time", "(UTC+02:00) Kaliningrad"),
    ("047", "South Africa Standard Time", "(UTC+02:00) Harare, Pretoria"),
    ("153", "Sudan Standard Time", "(UTC+02:00) Khartoum"),
    ("051", "Syria Standard Time", "(UTC+03:00) Damascus"),
    ("133", "West Bank Gaza Standard Time", "(UTC+02:00) Gaza, Hebron"),
    ("054", "Arab Standard Time", "(UTC+03:00) Kuwait, Riyadh"),
    ("056", "Arabic Standard Time", "(UTC+03:00) Baghdad"),
    ("114", "Belarus Standard Time", "(UTC+03:00) Minsk"),
    ("055", "E. Africa Standard Time", "(UTC+03:00) Nairobi"),
    ("117", "Russia TZ 2 Standard Time", "(UTC+03:00) Moscow, St. Petersburg, Volgograd"),
    ("052", "Turkey Standard Time", "(UTC+03:00) Istanbul"),
    ("058", "Iran Standard Time", "(UTC+03:30) Tehran"),
    ("060", "Arabian Standard Time", "(UTC+04:00) Abu Dhabi, Muscat"),
    ("130", "Astrakhan Standard Time", "(UTC+04:00) Astrakhan, Ulyanovsk"),
    ("062", "Azerbaijan Standard Time", "(UTC+04:00) Baku"),
    ("061", "Caucasus Standard Time", "(UTC+04:00) Yerevan"),
    ("059", "Georgian Standard Time", "(UTC+04:00) Tbilisi"),
    ("063", "Mauritius Standard Time", "(UTC+04:00) Port Louis"),
    ("132", "Russia TZ 3 Standard Time", "(UTC+04:00) Izhevsk, Samara"),
    ("154", "Saratov Standard Time", "(UTC+04:00) Saratov"),
    ("064", "Afghanistan Standard Time", "(UTC+04:30) Kabul"),
    ("067", "Pakistan Standard Time", "(UTC+05:00) Islamabad, Karachi"),
    ("122", "Russia TZ 4 Standard Time", "(UTC+05:00) Ekaterinburg"),
    ("066", "West Asia Standard Time", "(UTC+05:00) Ashgabat, Tashkent"),
    ("068", "India Standard Time", "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi"),
    ("069", "Sri Lanka Standard Time", "(UTC+05:30) Sri Jayawardenepura"),
    ("070", "Nepal Standard Time", "(UTC+05:45) Kathmandu"),
    ("073", "Bangladesh Standard Time", "(UTC+06:00) Dhaka"),
    ("071", "Central Asia Standard Time", "(UTC+05:00) Astana"),
    ("129", "Omsk Standard Time", "(UTC+06:00) Omsk"),
    ("074", "Myanmar Standard Time", "(UTC+06:30) Yangon (Rangoon)"),
    ("146", "Altai Standard Time", "(UTC+07:00) Barnaul, Gorno-Altaysk"),
    ("140", "Novosibirsk Standard Time", "(UTC+07:00) Novosibirsk"),
    ("118", "Russia TZ 6 Standard Time", "(UTC+07:00) Krasnoyarsk"),
    ("075", "SE Asia Standard Time", "(UTC+07:00) Bangkok, Hanoi, Jakarta"),
    ("135", "Tomsk Standard Time", "(UTC+07:00) Tomsk"),
    ("134", "W. Mongolia Standard Time", "(UTC+07:00) Hovd"),
    ("077", "China Standard Time", "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi"),
    ("081", "Malay Peninsula Standard Time", "(UTC+08:00) Kuala Lumpur, Singapore"),
    ("119", "Russia TZ 7 Standard Time", "(UTC+08:00) Irkutsk"),
    ("105", "Singapore Standard Time", "(UTC+08:00) Singapore"),
    ("078", "Taipei Standard Time", "(UTC+08:00) Taipei"),
    ("082", "Ulaanbaatar Standard Time", "(UTC+08:00) Ulaanbaatar"),
    ("079", "W. Australia Standard Time", "(UTC+08:00) Perth"),
    ("148", "Aus Central W. Standard Time", "(UTC+08:45) Eucla"),
    ("083", "Korea Standard Time", "(UTC+09:00) Seoul"),
    ("149", "North Korea Standard Time", "(UTC+09:00) Pyongyang"),
    ("115", "Russia TZ 8 Standard Time", "(UTC+09:00) Yakutsk"),
    ("084", "Tokyo Standard Time", "(UTC+09:00) Osaka, Sapporo, Tokyo"),
    ("131", "Transbaikal Standard Time", "(UTC+09:00) Chita"),
    ("086", "AUS Central Standard Time", "(UTC+09:30) Darwin"),
    ("087", "Cen. Australia Standard Time", "(UTC+09:30) Adelaide"),
    ("088", "AUS Eastern Standard Time", "(UTC+10:00) Canberra, Melbourne, Sydney"),
    ("089", "E. Australia Standard Time", "(UTC+10:00) Brisbane"),
    ("116", "Russia TZ 9 Standard Time", "(UTC+10:00) Vladivostok"),
    ("090", "Tasmania Standard Time", "(UTC+10:00) Hobart"),
    ("092", "West Pacific Standard Time", "(UTC+10:00) Guam, Port Moresby"),
    ("141", "Lord Howe Standard Time", "(UTC+10:30) Lord Howe Island"),
    ("145", "Bougainville Standard Time", "(UTC+11:00) Bougainville Island"),
    ("093", "Central Pacific Standard Time", "(UTC+11:00) Solomon Is., New Caledonia"),
    ("094", "Magadan Standard Time", "(UTC+11:00) Magadan"),
    ("139", "Norfolk Standard Time", "(UTC+11:00) Norfolk Island"),
    ("125", "Russia TZ 10 Standard Time", "(UTC+11:00) Chokurdakh"),
    ("137", "Sakhalin Standard Time", "(UTC+11:00) Sakhalin"),
    ("095", "Fiji Standard Time", "(UTC+12:00) Fiji"),
    ("096", "New Zealand Standard Time", "(UTC+12:00) Auckland, Wellington"),
    ("126", "Russia TZ 11 Standard Time", "(UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky"),
    ("097", "UTC+12", "(UTC+12:00) Coordinated Universal Time +12"),
    ("144", "Chatham Islands Standard Time", "(UTC+12:45) Chatham Islands"),
    ("001", "Samoa Standard Time", "(UTC+13:00) Samoa"),
    ("098", "Tonga Standard Time", "(UTC+13:00) Nuku'alofa"),
    ("157", "UTC+13", "(UTC+13:00) Coordinated Universal Time+13"),
    ("123", "Line Islands Standard Time", "(UTC+14:00) Kiritimati Island"),
]


def timezone_choices() -> list[tuple[str, str]]:
    """Return (value, label) pairs for timezone selection.

    Value is the numeric ID string sent to ``TIMEZONE <id>``.
    Label is a human-readable string for display.
    """
    return [
        (tz_id, f"{tz_id.lstrip('0') or '0':>3}  {offset}  {name}")
        for tz_id, name, offset in TIMEZONES
    ]


def timezone_label(tz_id: str) -> str:
    """Return a human-readable label for a timezone ID, or the raw ID if unknown."""
    padded = tz_id.zfill(3)
    for tid, name, offset in TIMEZONES:
        if tid == padded:
            return f"{name} {offset}"
    return tz_id
